apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-web-editor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Tempestyash123456/Online-Code-Editor-Python.git"
    targetRevision: main
    path: argocd_declarative
  destination:
    server: "https://172.31.35.35:33893"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
