apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-editor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: code-editor
  template:
    metadata:
      labels:
        app: code-editor
    spec:
      containers:
      - name: code-editor
          image: tempestyashdubey/code-editor:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
